-- Domain Registry Table
CREATE TABLE IF NOT EXISTS domain_registry (
    id INT AUTO_INCREMENT PRIMARY KEY,
    domain VARCHAR(191) NOT NULL UNIQUE,
    domain_id VARCHAR(255),
    status VARCHAR(50),
    registrar_name VARCHAR(255),
    registrar_iana_id VARCHAR(50),
    registrar_url VARCHAR(500),
    create_date DATETIME,
    update_date DATETIME,
    expire_date DATETIME,
    whois_server VARCHAR(255),
    domain_age INT,
    registrant_name VARCHAR(255),
    registrant_organization VARCHAR(255),
    registrant_email VARCHAR(255),
    registrant_phone VARCHAR(50),
    registrant_country VARCHAR(100),
    admin_name VARCHAR(255),
    admin_organization VARCHAR(255),
    admin_email VARCHAR(255),
    admin_phone VARCHAR(50),
    tech_name VARCHAR(255),
    tech_organization VARCHAR(255),
    tech_email VARCHAR(255),
    tech_phone VARCHAR(50),
    billing_name VARCHAR(255),
    billing_organization VARCHAR(255),
    billing_email VARCHAR(255),
    billing_phone VARCHAR(50),
    nameservers JSON,
    raw_data JSON,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_by INT,
    FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
    INDEX idx_domain (domain),
    INDEX idx_expire_date (expire_date),
    INDEX idx_created_by (created_by)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Domain Query Log Table (for rate limiting)
CREATE TABLE IF NOT EXISTS domain_query_log (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    domain VARCHAR(191) NOT NULL,
    query_date DATE NOT NULL,
    query_count INT DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    UNIQUE KEY unique_user_domain_date (user_id, domain, query_date),
    INDEX idx_user_date (user_id, query_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
