//go:build ignore
// +build ignore

package main

// This program generates internal/network/scanner/oui_data_generated.go
// from an IEEE oui.txt file. Usage:
//
//   SYSTRACK_OUI_SOURCE=/path/to/oui.txt go generate ./internal/network/scanner
//
// If SYSTRACK_OUI_SOURCE is unset, the generator looks for data/oui.txt.

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/klauspost/oui"
)

func main() {
	source := strings.TrimSpace(os.Getenv("SYSTRACK_OUI_SOURCE"))
	if source == "" {
		source = filepath.Join("data", "oui.txt")
	}

	f, err := os.Open(source)
	if err != nil {
		panic(fmt.Errorf("open OUI source %q: %w", source, err))
	}
	defer f.Close()

	db, err := oui.OpenStatic(f)
	if err != nil {
		panic(fmt.Errorf("parse OUI data: %w", err))
	}

	rawGetter, ok := db.(oui.RawGetter)
	if !ok {
		panic("unable to obtain raw OUI entries")
	}

	raw := rawGetter.RawDB()
	keys := make([][3]byte, 0, len(raw))
	for k := range raw {
		keys = append(keys, k)
	}

	sort.Slice(keys, func(i, j int) bool {
		if keys[i][0] != keys[j][0] {
			return keys[i][0] < keys[j][0]
		}
		if keys[i][1] != keys[j][1] {
			return keys[i][1] < keys[j][1]
		}
		return keys[i][2] < keys[j][2]
	})

	var buf bytes.Buffer
	buf.WriteString("package scanner\n\n")
	buf.WriteString("// Code generated by internal/network/scanner/oui_gen.go; DO NOT EDIT.\n")
	buf.WriteString("var generatedOUIData = map[[3]byte]string{\n")
	for _, key := range keys {
		entry := raw[key]
		vendor := strings.TrimSpace(entry.Manufacturer)
		if vendor == "" && len(entry.Address) > 0 {
			vendor = strings.TrimSpace(entry.Address[0])
		}
		if vendor == "" {
			vendor = strings.TrimSpace(entry.Country)
		}
		if vendor == "" {
			continue
		}
		fmt.Fprintf(&buf, "\t{%d, %d, %d}: %q,\n", key[0], key[1], key[2], vendor)
	}
	buf.WriteString("}\n")

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		panic(fmt.Errorf("format generated code: %w", err))
	}

	outputPath := filepath.Join("internal", "network", "scanner", "oui_data_generated.go")
	if err := os.WriteFile(outputPath, formatted, 0o644); err != nil {
		panic(fmt.Errorf("write output file: %w", err))
	}
}
